export const REPOSITORY_URL = "https://github.com/wuchaozju/GAWorld";
export const QUICK_START = ["pip install -r requirements.txt", "python generative_city_sim.py run"] as const;

export type Locale = "zh" | "en";

const shared = {
  commands: QUICK_START,
  repository: REPOSITORY_URL,
};

export const CONTENT = {
  zh: {
    ...shared,
    langName: "English",
    nav: ["核心能力", "系统架构", "快速开始"],
    eyebrow: "生成式城市社会实验沙盒",
    title: "让一座城市成为可重放、可干预、可比较的社会实验。",
    intro: "GAWorld 将长期记忆、社会影响、环境事件、政策冲击、闭环经济与 LLM 决策组合成可检查的多智能体仿真工作流。",
    github: "在 GitHub 查看",
    run: "一分钟运行",
    signals: ["长期智能体记忆", "社会网络演化", "家庭与共居", "政策与环境冲击", "闭环经济", "地图化行动", "可回放轨迹", "月 / 年尺度长跑"],
    loopTitle: "从感知到记忆的持续循环",
    loopBody: "每个智能体在环境与社会关系中行动，并让经历持续改变之后的选择。",
    loop: ["感知", "规划", "行动", "反思", "记忆更新"],
    capabilitiesTitle: "为研究可控，为开发可用",
    capabilitiesBody: "同一套模块既支撑反事实实验，也提供可扩展的工程边界。",
    capabilities: [
      ["记忆、人格与行为一致性", "研究跨日经历如何改变意图、习惯与关系，以及每位居民的五维人格（开放性、尽责性、外向性、宜人性、神经质）如何持续偏置行动选择、打断难度、同处时的搭话频率、消费与储蓄倾向和情绪回落点。", "检查情景记忆、长期摘要、习惯与意图产物；人格分规则、提示词、日记三条可独立开关的通道，规则通道零 LLM 开销，得分离线标定一次后冻结在 data/agents_big5.csv，运行期不漂移。"],
      ["社会与政策干预", "比较事件、推荐暴露与政策冲击的反事实结果。", "通过可配置事件和干预模块复现实验。"],
      ["空间、家庭与经济系统", "观察通勤、拥挤、消费、税收与宏观周期的联动，以及婚育、共居与照护负担如何改变一个人的时间、金钱与情绪。", "组合城市地图、位置系统、资金守恒经济模块与家庭模块——家庭可按人口学分布生成，也可逐人精确指定并跨运行生效。"],
    ],
    research: "研究视角",
    developer: "开发视角",
    scenariosTitle: "把复杂社会问题变成可运行实验",
    scenarios: [
      ["城市治理", "比较交通限制、公共服务、生育与养老政策以及突发事件下的群体响应。"],
      ["社会传播", "研究情绪、风险、观点在关系网络与家庭内部的扩散。"],
      ["行为一致性", "评估长期记忆、习惯和冻结的五维人格特质对决策的影响，并把「文风变了」和「决策变了」分开验证。"],
      ["复杂系统教学", "用可检查轨迹展示微观行为如何形成宏观结果。"],
    ],
    quickTitle: "一分钟启动你的第一座城市",
    quickBody: "安装依赖，然后运行默认仿真。",
    copy: "复制",
    copied: "已复制",
    manual: "请手动选择并复制命令",
    architectureTitle: "一座城市，多个可组合系统",
    architectureBody: "智能体通过环境感知、社会关系和经济约束行动，再把结果写回记忆。",
    modules: [["Agent Core", "身份、五维人格特质、状态与并发执行"], ["Memory", "经历、习惯、意图与总结"], ["Environment", "天气、事件、位置与异常"], ["Social", "关系、影响与群体传播"], ["Economy", "收入、消费、税收、信用与周期"], ["Family", "婚姻、共居、家庭日程、育儿与赡养开销"], ["Policy", "干预、暴露与反事实指标"]],
    ctaEyebrow: "OPEN SOURCE · 开源",
    ctaTitle: "从代码开始理解这座城市",
    ctaBody: "阅读架构，运行默认仿真，再用自己的智能体、事件和政策扩展 GAWorld。",
    docs: "阅读项目文档",
    dashboard: "启动本地 Dashboard",
  },
  en: {
    ...shared,
    langName: "中文",
    nav: ["Capabilities", "Architecture", "Quick start"],
    eyebrow: "A generative urban social experiment sandbox",
    title: "Turn a city into a replayable, intervenable, comparable social experiment.",
    intro: "GAWorld combines long-term memory, social influence, environmental events, policy shocks, a closed-loop economy, and LLM decisions in an inspectable multi-agent workflow.",
    github: "View on GitHub",
    run: "Run in one minute",
    signals: ["Long-term memory", "Evolving social graph", "Households and co-residence", "Policy and event shocks", "Closed-loop economy", "Map-based action", "Replayable traces", "Multi-year horizons"],
    loopTitle: "A continuous loop from perception to memory",
    loopBody: "Agents act inside an environment and social graph, then carry each experience into later choices.",
    loop: ["Perceive", "Plan", "Act", "Reflect", "Update memory"],
    capabilitiesTitle: "Controlled for research. Practical for builders.",
    capabilitiesBody: "The same modules support counterfactual experiments and clear extension points.",
    capabilities: [
      ["Memory, personality, and consistency", "Study how experiences reshape intentions, habits, and relationships across days — and how each resident's five traits (openness, conscientiousness, extraversion, agreeableness, neuroticism) keep tilting action choice, how hard they are to interrupt, how often they strike up a conversation, spending versus saving, and where their mood settles back.", "Inspect episodic memory, long-term summaries, habits, and intentions; personality ships as three independently switchable channels — rules, prompt, and diary voice — where the rules channel spends zero LLM tokens and scores are calibrated once offline, then frozen to data/agents_big5.csv and never drift during a run."],
      ["Social and policy intervention", "Compare counterfactual outcomes under events, exposure, and policy shocks.", "Reproduce experiments through configurable event and intervention modules."],
      ["Spatial, household, and economic systems", "Observe interactions among commuting, crowding, spending, taxation, and macro cycles — and how marriage, children, co-residence, and care load reshape a person's time, money, and mood.", "Compose the city map, location system, money-conserving economy, and households — generated from demographic distributions or pinned resident by resident."],
    ],
    research: "For research",
    developer: "For builders",
    scenariosTitle: "Turn complex social questions into runnable experiments",
    scenarios: [["Urban governance", "Compare group responses to mobility restrictions, public services, fertility and elder-care policy, and emergencies."], ["Social propagation", "Study emotion, risk, opinion, and influence across relationships and inside households."], ["Behavioral consistency", "Evaluate how memory, habits, and frozen Big Five traits shape decisions, and tell “the writing changed” apart from “the decisions changed”."], ["Complex-systems education", "Use inspectable traces to connect micro behavior with macro outcomes."]],
    quickTitle: "Launch your first city in one minute",
    quickBody: "Install the dependencies, then run the default simulation.",
    copy: "Copy",
    copied: "Copied",
    manual: "Select and copy the command manually",
    architectureTitle: "One city, multiple composable systems",
    architectureBody: "Agents act through environmental perception, social ties, and economic constraints, then write outcomes back to memory.",
    modules: [["Agent Core", "Identity, Big Five personality traits, state, and concurrent execution"], ["Memory", "Experience, habits, intentions, and summaries"], ["Environment", "Weather, events, locations, and anomalies"], ["Social", "Relationships, influence, and propagation"], ["Economy", "Income, spending, tax, credit, and cycles"], ["Family", "Marriage, co-residence, family duties, childcare and elder support"], ["Policy", "Intervention, exposure, and counterfactual metrics"]],
    ctaEyebrow: "OPEN SOURCE",
    ctaTitle: "Understand the city from its code",
    ctaBody: "Read the architecture, run the default simulation, then extend GAWorld with your own agents, events, and policies.",
    docs: "Read project docs",
    dashboard: "Launch local Dashboard",
  },
} as const;
