"""CLI: ``python -m gaworld.group``.

Runs group-mode simulation over a generated population. With ``--no-llm`` the
whole run is deterministic and free, which is how the cost accounting below is
produced without spending anything.

Examples::

    # 500-person town, 7 days, deterministic (no LLM calls)
    python -m gaworld.group --size 500 --days 7 --no-llm

    # follow two specific residents at full fidelity
    python -m gaworld.group --size 500 --days 7 --focal 7,42 --no-llm

    # with the social-graph coupling that lets the validation gate's L2 pass
    python -m gaworld.group --size 500 --days 7 --network-coupling 0.7 --no-llm

    # use a population already generated by `python -m gaworld.population`
    python -m gaworld.group --population data/town/generated_town_state_init.csv --no-llm
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

from gaworld.group.driver import GroupRunConfig, render_day_block, run_group_simulation
from gaworld.population.generate import generate_population
from gaworld.population.schema import PRESETS, STATE_VAR_KEYS, normalize_spec


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m gaworld.group",
        description="Run group-mode (cohort) simulation over a synthetic population.",
    )
    source = parser.add_argument_group("population source")
    source.add_argument("--population", type=Path, help="Existing state CSV to load")
    source.add_argument("--size", type=int, default=500, help="Generate this many residents")
    source.add_argument("--preset", choices=sorted(PRESETS), default="cn_county_town")
    source.add_argument("--seed", type=int, default=42)

    run = parser.add_argument_group("run")
    run.add_argument("--days", type=int, default=7)
    run.add_argument("--axes", help="Comma-separated cohort axes (default: age_band,industry,hukou)")
    run.add_argument("--budget", type=int, default=20, help="Individuals materialised per day")
    run.add_argument("--audit-fraction", type=float, default=0.03)
    run.add_argument("--focal", help="Comma-separated agent ids to always materialise")
    run.add_argument(
        "--network-coupling",
        type=float,
        default=0.0,
        help=(
            "Within-cohort mean-zero social-graph coupling (0 = off). Needs a social graph, "
            "so it is unavailable with --population (a state CSV carries no edges)."
        ),
    )
    run.add_argument("--no-llm", action="store_true", help="Deterministic run, zero LLM calls")

    out = parser.add_argument_group("output")
    out.add_argument("--verbose", action="store_true", help="Print each day's cohort briefs")
    out.add_argument("--json", action="store_true", help="Emit the full run record as JSON")
    out.add_argument("--out", type=Path, help="Write the run record to this directory")
    return parser


def _load_agents_from_csv(path: Path) -> list[dict[str, Any]]:
    """Load a state CSV. Cohort axes absent from the CSV degrade gracefully.

    The state CSV carries id/name/gender/age/hukou/residence plus the nine state
    variables — it has no ``industry`` column, since the individual tier infers
    industry from job text. Partitioning therefore falls back to whatever axes
    the data supports; ``--axes`` should be set accordingly.
    """
    agents: list[dict[str, Any]] = []
    with open(path, encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            agents.append(
                {
                    "id": int(row["id"]),
                    "name": row.get("name", ""),
                    "age": int(row.get("age") or 0),
                    "gender": row.get("gender", ""),
                    "hukou": row.get("hukou", ""),
                    "residence": row.get("residence", ""),
                    "state": {key: float(row.get(key, 0.5) or 0.5) for key in STATE_VAR_KEYS},
                }
            )
    return agents


def _agents_from_generated(
    size: int, seed: int, preset: str
) -> tuple[list[dict[str, Any]], dict[int, list[int]]]:
    """Generate a population and return its agents *and* its social graph.

    The graph is returned alongside because ``--network-coupling`` needs it;
    regenerating it separately would risk the two drifting apart.
    """
    result = generate_population(normalize_spec({"size": size, "seed": seed, "preset": preset}))
    agents = [
        {
            "id": person.id,
            "name": person.name,
            "age": person.age,
            "gender": person.gender,
            "hukou": person.hukou,
            "industry": person.industry,
            "employment": person.employment,
            "residence": person.residence,
            "district": person.district,
            "state": dict(person.state),
        }
        for person in result.people
    ]
    return agents, {int(k): list(v) for k, v in result.neighbours.items()}


def _parse_ids(raw: str | None) -> list[int]:
    if not raw:
        return []
    return [int(part) for part in str(raw).replace(" ", "").split(",") if part]


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    neighbours: dict[int, list[int]] | None = None
    if args.population:
        agents = _load_agents_from_csv(args.population)
        default_axes: tuple[str, ...] = ("age_band", "hukou")
        if args.network_coupling > 0:
            # Fail loudly rather than silently running without the coupling the
            # user asked for — that would look like the network mechanism was
            # active when it was not.
            print(
                "--network-coupling 需要社交图，而 state CSV 不含边。" "请改用 --size 现场生成人口。",
                flush=True,
            )
            return 1
    else:
        agents, neighbours = _agents_from_generated(args.size, args.seed, args.preset)
        default_axes = ("age_band", "industry", "hukou")
    if not agents:
        print("没有可用的人口数据。", flush=True)
        return 1

    axes = tuple(args.axes.replace(" ", "").split(",")) if args.axes else default_axes
    cfg = GroupRunConfig(
        days=args.days,
        cohort_axes=axes,
        materialization_budget=args.budget,
        audit_fraction=args.audit_fraction,
        focal_ids=_parse_ids(args.focal),
        use_llm=not args.no_llm,
        seed=args.seed,
        network_coupling=args.network_coupling,
    )

    llm_fn = None
    if cfg.use_llm:
        from gaworld.llm import providers as llm_providers

        llm_fn = llm_providers.call_llm
        # State the bill before running it. Without --no-llm this command makes
        # real API calls, and the count is a function of cohort count (not
        # headcount), which is not obvious from the arguments the user typed.
        from gaworld.group.cohort import partition_cohorts

        estimated = len(partition_cohorts(agents, axes=axes, min_size=cfg.min_cohort_size))
        print(
            f"⚠️  将调用真实 LLM：约 {estimated * cfg.days} 次"
            f"（{estimated} 个群体 × {cfg.days} 天）"
            f"{f'，另加实体化个体 {cfg.materialization_budget}×{cfg.days} 人-天' if cfg.materialization_budget else ''}。"
            f"加 --no-llm 可零成本试跑。",
            flush=True,
        )

    result = run_group_simulation(agents, cfg, llm_fn=llm_fn, neighbours=neighbours)

    if args.json:
        print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2))
    else:
        if args.verbose:
            for day in range(1, cfg.days + 1):
                print(render_day_block(result, day))
        cost = result.cost_summary()
        print(f"群体模拟完成：{cost['population']} 人 → {cost['cohorts']} 个群体，" f"{cost['days']} 天")
        print(f"  LLM 调用（实测）：{cost['group_llm_calls']}")
        print(f"  实体化个体-天：{cost['individual_agent_days']}")
        print(
            f"  全个体模拟估算：{cost['full_individual_llm_calls_estimate']}"
            f"（按 {cost['assumed_calls_per_agent_day']} 次/人/天）"
        )
        if cost["savings_factor"]:
            print(f"  成本比：约 {cost['savings_factor']:.0f}× 省")
        else:
            print("  成本比：本次未调用 LLM（--no-llm），故不可比")
        worst = max((d.max_residual_l1 for d in result.days), default=0.0)
        print(f"  审计残差 L1 最大：{worst:.4f}")

    if args.out:
        args.out.mkdir(parents=True, exist_ok=True)
        target = args.out / "group_run.json"
        target.write_text(json.dumps(result.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8")
        if not args.json:
            print(f"  已写出：{target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
