"""Skill subsystem for GAWorld agents.

A *Skill* is a small, reusable capability that an agent can hold and
draw on while reasoning or producing work. It is intentionally modelled
on Claude Code skills:

* Each skill lives on disk as a Markdown file with a YAML frontmatter
  header (``name``, ``description``, optional ``triggers``).
* Skills live in two places:
    - ``data/skills/*.md`` — global, hand-authored library shared by
      every agent in the simulation.
    - ``output/memory/agent_{id}_skills/*.md`` — *private* skills
      generated by the agent itself by summarising its own experience.
* :class:`gaworld.skills.registry.SkillRegistry` is the single
  read/write surface.

The schema is deliberately tiny — these objects flow through prompts
and disk, not network APIs, so we keep them as plain dataclasses.
"""

from __future__ import annotations

from gaworld.skills.consolidation import (
    run_skill_consolidation,
    summarize_experience_to_skill,
)
from gaworld.skills.prompt_helpers import (
    relevant_skills_for_text,
    render_agent_skills,
)
from gaworld.skills.registry import SkillRegistry
from gaworld.skills.schemas import Skill, SkillSource

__all__ = [
    "Skill",
    "SkillRegistry",
    "SkillSource",
    "relevant_skills_for_text",
    "render_agent_skills",
    "run_skill_consolidation",
    "summarize_experience_to_skill",
]
